trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'To Azure connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t crgameapp.azurecr.io/web-game:tag 2048-game
      az acr login -n crgameapp
      docker push crgameapp.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'To Azure connection'
    azureResourceGroup: 'rg-game-app'
    kubernetesCluster: 'AKSgameApp'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'To Azure connection'
    azureContainerRegistry: 'crgameapp.azurecr.io'
    forceUpdate: false